python -u run.py \
  --task_name short_term_forecast \
  --is_training 1 \
  --root_path ./dataset/byd/ \
  --data_path byd_60.csv\
  --model_id bydyyy \
  --mask_rate 0.125 \
  --model TimesNet \
  --data custom \
  --features MS \
  --seq_len 48 \
  --label_len 0 \
  --pred_len 12 \
  --e_layers 2 \
  --d_layers 1 \
  --target close \
  --factor 3 \
  --enc_in 6 \
  --dec_in 6 \
  --c_out 6 \
  --batch_size 16 \
  --d_model 64 \
  --d_ff 64 \
  --des 'Exp' \
  --itr 1 \
  --top_k 3 \
  --learning_rate 0.001 \
  --loss 'SMAPE' 